//! What the server tells a client about itself: its instructions and each
//! tool's description. A client reads them in every session, before any
//! answer, so they hold only what no answer can say: what a tool gives, when
//! it helps and what it cannot see. What a mark, heading or count means is
//! said in the answers. They name no capability archmap lacks and prescribe
//! no order.

pub const INSTRUCTIONS: &str = "archmap maps a repository's structure from its manifests and imports: components (packages, modules, files, external dependencies), their public symbols and the dependencies between them, each with file:line evidence, for Rust, Python and TypeScript/JavaScript. Reach for it before searching a repository by hand to find where code lives, what a target exposes, what depends on what and what a change could affect: `summary` maps the repository, `query` shows one target with locations to open, `impact` lists what a change may reach, `check` compares the code with the rules in an archmap.toml. Everything is observed, not inferred: names are package and module names, not roles, and runtime coupling (HTTP, databases, queues, dynamic loading) is not seen, so a missing edge is not a missing dependency. Answers say what their marks mean; query and impact end with what they may miss (`Not traced`). Tools read the project directory unless given `path`.";

pub const SUMMARY: &str = "Map of a repository: its components, the dependencies observed between them in manifests and imports, and what the scan could not read (`## Coverage`). Use it to find where code lives or to choose what to query. Lists are capped; an `omitted:` line names the query for the rest.";

pub const QUERY: &str = "One target in detail, with file:line locations to open: its public symbols, its dependencies both ways with example import statements, the statements that import it, imports no edge shows (`Not mapped`), and for a symbol where code uses it (`Used at`). An issue or pull request (`#123`) answers from the snapshot `archmap fetch github` writes, with the files its commits changed, and a file or component ends with the work that snapshot links to the commits that changed it. A target that names several things lists candidates to retry with. Recommended before searching for a name or inside a component: its locations are the places to open first. `format: json` returns all evidence and can run to tens of KB for a busy component.";

pub const IMPACT: &str = "What may be affected by changing a file, symbol, component, directory or import name: the components that import it directly and those reached through them, the import statements with file:line locations, for a symbol where code uses it, the test files to run again with how each reaches it, the files changed in the same commits in the git history, and the pull requests and issues a work snapshot links to those commits. Use it before changing a public symbol, a signature or a dependency. It is reachability through imports, not a verdict: listed components may not use what changes, and no importers is no proof of no use, since framework entry files and code loaded by name or path have none by design. Runtime coupling is not followed. Lists are capped; `verbose` lists every entry, and `format: json` every entry with all evidence, which for a busy target runs large.";

pub const CHECK: &str = "Compares the repository with the dependency rules declared in its archmap.toml (forbidden dependencies, layers, allow lists, cycles, undeclared imports) and reports structural signals. Use it after a change in a repository that has an archmap.toml. Findings carry evidence; signals are observations, never failures. Without an archmap.toml it reports signals only.";
