//! What the server tells a client about itself: its instructions and each
//! tool's description. They say what a tool gives, when it helps and what it
//! cannot see; they name no capability archmap lacks and prescribe no order.

pub const INSTRUCTIONS: &str = "archmap maps a repository's structure from its manifests and imports: components (packages, modules, files, external dependencies), their public symbols and the dependencies between them, each with file:line evidence, for Rust, Python and TypeScript/JavaScript. Reach for it before searching a repository by hand to find where code lives, what a component, file or symbol exposes, what depends on what, and what a change could affect. `summary` maps the repository, `query` shows one target in detail with locations to open (for a TypeScript or JavaScript symbol, also where code uses it), `impact` lists what a change to a target may reach, and `check` compares the code with the rules in an archmap.toml. Targets are paths (absolute or relative to the root) or names. Everything is observed, not inferred: names are package and module names, not roles, and runtime coupling (HTTP, databases, queues, dynamic loading) is not seen, so a missing edge is not a missing dependency. Tools read the project directory unless given `path`.";

pub const SUMMARY: &str = "Map of a repository: its components (packages, modules, files, external dependencies), the dependencies observed between them in manifests and imports, and what the scan could not read (`## Coverage`). Use it to find where code lives or to choose what to query. Lists are capped; an `omitted:` line names the query that shows the rest. Facts only: names are package and module names, not roles, and runtime coupling (HTTP, databases, queues, dynamic loading) is not seen.";

pub const QUERY: &str = "One target in detail, with file:line locations to open: public symbols, dependencies in both directions with example import statements, the statements that import a file or symbol, and imports that no edge shows (`Not mapped`). For a TypeScript or JavaScript symbol, `Used at` lists where code uses it, read from the file that defines it and the files that import it: calls, `new`, JSX elements, types and other uses, through the names imports bind and, for a method, through its class and `this`; names in comments and strings are no uses. When the target names several things, the answer lists them as candidates to retry with. It ends with what could reach the target unseen (`Not traced`), when anything applies. Recommended before searching for a name or inside a component: its locations are the places to open first. An importer's location is where its import is written, not where the name is used. Not seen: where a Rust or Python symbol is used beyond its imports, a method called through a value of its type, and runtime coupling. `format: json` returns all evidence and can run to tens of KB for a busy component.";

pub const IMPACT: &str = "What may be affected by changing a file, symbol, component, directory or an import name: the components whose code imports it directly (for a Python package's `__init__.py`, also a module below it), those reached only through them, the import statements with file:line locations (where each import is written, not where the name is used), the test files to run again, and what could reach it unseen (`Not traced`). Use it before changing a public symbol, a signature or a dependency. It is reachability through imports, not a verdict: listed components may not use what changes, and no importers is no proof of no use, since framework entry files and code loaded by name or path have none by design. Uses inside the file that defines a symbol are no imports, so they are not listed. Runtime coupling (HTTP, end-to-end tests over HTTP, databases, dynamic loading) is not followed. Lists are capped and count the rest; `verbose` lists every entry, and `format: json` gives the same lists as JSON.";

pub const CHECK: &str = "Compares the repository with the dependency rules declared in its archmap.toml (forbidden dependencies, layers, allow lists, cycles, undeclared imports) and reports structural signals. Use it after a change in a repository that has an archmap.toml. Findings carry evidence; signals are observations, never failures. Without an archmap.toml it reports signals only.";
